# Generated by Django 4.0.3 on 2022-03-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('datetime_session_expires', models.DateTimeField()),
                ('target_view_name', models.CharField(max_length=75)),
                ('is_verified', models.BooleanField(default=False)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('datetime_verified_session_expires', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
