# Generated by Django 4.0.3 on 2022-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsession',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
